query Recipe($recipeId: String!) {
	recipe(id: $recipeId) {
		id
		title
		tutorialVideo
		previewPicture
		difficulty
		portion
		steps
		cookingTime
		ingredients {
            ingredientId
			name
			quantity
			mesureUnit
		}
		tags {
            tagId
		}
	}
}
