name: ESLint Check

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - name: ESLint check
        run: pnpm lint

      - name: Check if any errors
        id: eslint-status
        run: echo ::set-output name=has_errors::$(git diff --name-only origin/main | grep '\.jsx\?$' | xargs eslint --max-warnings=0 --format=compact || true)

      - name: Fail if there are errors
        run: |
          if [ "${{ steps.eslint-status.outputs.has_errors }}" != "" ]; then
            echo "ESLint check failed"
            exit 1
          fi
