// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CounterPortion: typeof import('./recipe/pages/recipe/components/counterPortion.vue')['default']
    EmailInput: typeof import('./common/components/forms/EmailInput.vue')['default']
    BurgerMenuButton: typeof import('./layout/components/BurgerMenuButton.vue')['default']
    BurgerMenuLinks: typeof import('./layout/components/BurgerMenuLinks.vue')['default']
    CardRecipe: typeof import('./common/components/forms/CardRecipe.vue')['default']
    CloseDrawer: typeof import('./layout/components/CloseDrawer.vue')['default']
    ConnexionButton: typeof import('./layout/components/ConnexionButton.vue')['default']
    DeconnexionButton: typeof import('./layout/components/DeconnexionButton.vue')['default']
    DesktopNavbar: typeof import('./layout/components/DesktopNavbar.vue')['default']
    DifficultiesFilter: typeof import('./recipe-list/components/filters/recipe-list-filter/filters/DifficultiesFilter.vue')['default']
    DifficultiesInput: typeof import('./recipe-list/components/filters/inputs/DifficultiesInput.vue')['default']
    EmailInput: typeof import('./common/components/forms/EmailInput.vue')['default']
    Footer: typeof import('./layout/components/Footer.vue')['default']
    FormIngredient: typeof import('./ingredient-new/components/FormIngredient.vue')['default']
    FormRecipe: typeof import('./recipe-new/components/FormRecipe.vue')['default']
    IngredientsFilter: typeof import('./recipe-list/components/filters/recipe-list-filter/filters/IngredientsFilter.vue')['default']
    Input: typeof import('./recipe-new/components/Input.vue')['default']
    Link: typeof import('./layout/components/Link.vue')['default']
    LoginForm: typeof import('./authentication/components/login/LoginForm.vue')['default']
    LoginLink: typeof import('./authentication/components/login/LoginLink.vue')['default']
    MaximumTimeCookingFilter: typeof import('./recipe-list/components/filters/recipe-list-filter/filters/MaximumTimeCookingFilter.vue')['default']
    MaximumTimeCookingInput: typeof import('./recipe-list/components/filters/inputs/MaximumTimeCookingInput.vue')['default']
    MobileNavbar: typeof import('./layout/components/MobileNavbar.vue')['default']
    Navbar: typeof import('./layout/components/Navbar.vue')['default']
    NavbarIcon: typeof import('./layout/components/NavbarIcon.vue')['default']
    NavbarLinks: typeof import('./layout/components/NavbarLinks.vue')['default']
    NavbarSearch: typeof import('./layout/components/NavbarSearch.vue')['default']
    PaginationFilter: typeof import('./recipe-list/components/pagination/PaginationFilter.vue')['default']
    PasswordConfirmationInput: typeof import('./common/components/forms/PasswordConfirmationInput.vue')['default']
    RecipeCreatorConnectedUserFilter: typeof import('./recipe-list/components/filters/recipe-list-filter/filters/RecipeCreatorConnectedUserFilter.vue')['default']
    RecipeCreatorFilter: typeof import('./recipe-list/components/filters/recipe-list-filter/filters/RecipeCreatorFilter.vue')['default']
    RecipeList: typeof import('./recipe-list/components/list/RecipeList.vue')['default']
    RecipeListFilter: typeof import('./recipe-list/components/filters/recipe-list-filter/RecipeListFilter.vue')['default']
    RegisterForm: typeof import('./authentication/components/register/RegisterForm.vue')['default']
    RegisterLink: typeof import('./authentication/components/register/RegisterLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./recipe-new/components/Select.vue')['default']
    SelectAutocomplete: typeof import('./recipe-new/components/SelectAutocomplete.vue')['default']
    SelectMultiple: typeof import('./recipe-new/components/SelectMultiple.vue')['default']
    TagsFilter: typeof import('./recipe-list/components/filters/recipe-list-filter/filters/TagsFilter.vue')['default']
    Time: typeof import('./recipe-new/components/Time.vue')['default']
  }
}

export {}
