// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DifficultiesFilter: typeof import('./recipe-list/components/filters/recipe-list-filter/filters/DifficultiesFilter.vue')['default']
    DifficultiesInput: typeof import('./recipe-list/components/filters/inputs/DifficultiesInput.vue')['default']
    EmailInput: typeof import('./common/components/forms/EmailInput.vue')['default']
    IngredientsFilter: typeof import('./recipe-list/components/filters/recipe-list-filter/filters/IngredientsFilter.vue')['default']
    LoginForm: typeof import('./authentication/components/login/LoginForm.vue')['default']
    LoginLink: typeof import('./authentication/components/login/LoginLink.vue')['default']
    LogoutButton: typeof import('./authentication/components/LogoutButton.vue')['default']
    MaximumTimeCookingFilter: typeof import('./recipe-list/components/filters/recipe-list-filter/filters/MaximumTimeCookingFilter.vue')['default']
    MaximumTimeCookingInput: typeof import('./recipe-list/components/filters/inputs/MaximumTimeCookingInput.vue')['default']
    PaginationFilter: typeof import('./recipe-list/components/pagination/PaginationFilter.vue')['default']
    PasswordConfirmationInput: typeof import('./common/components/forms/PasswordConfirmationInput.vue')['default']
    RecipeCreatorConnectedUserFilter: typeof import('./recipe-list/components/filters/recipe-list-filter/filters/RecipeCreatorConnectedUserFilter.vue')['default']
    RecipeCreatorFilter: typeof import('./recipe-list/components/filters/recipe-list-filter/filters/RecipeCreatorFilter.vue')['default']
    RecipeList: typeof import('./recipe-list/components/list/RecipeList.vue')['default']
    RecipeListFilter: typeof import('./recipe-list/components/filters/recipe-list-filter/RecipeListFilter.vue')['default']
    RegisterForm: typeof import('./authentication/components/register/RegisterForm.vue')['default']
    RegisterLink: typeof import('./authentication/components/register/RegisterLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsFilter: typeof import('./recipe-list/components/filters/recipe-list-filter/filters/TagsFilter.vue')['default']
  }
}

export {}
